import { axios_base_url } from "@/appConstants/config";
import axios from "axios";
import Head from "next/head";
import DynamicContent from "./components/DynamicContent";
import Link from "next/link";

// getServerSideProps will run before the home function or any default function. If this fails, client will be redirected to 500 ERROR. See nextls documentation for more...
// In this file, we have first retrived all data from our server. for doing so, we have called
export async function getServerSideProps({ req, res }: any) {
  let data;

  try {
    const response = await axios.get(axios_base_url + "api/get_site_data");
    data = response.data.data;
  } catch (e) {
    console.log("Error");
  }

  return {
    props: {
      data:
        data && data.length > 0 ? JSON.stringify(data) : JSON.stringify([{}]),
    },
  };
}

export default function Home({ data }: any) {
  const main_data = JSON.parse(data);
  return (
    <>
      <Head>
        <title>next_stcms: CMS For NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="stc_main_container">
        <div className="stc_header">
          <h1>
            {" "}
            <DynamicContent
              dynamic_id="sub_intro"
              data={main_data}
              fallback_data={" Welcome to NEXT_STCMS"}
            />
          </h1>
        </div>

        <br />
        <div className="" style={{ fontSize: "25px" }}>
          <DynamicContent
            dynamic_id="intro"
            data={main_data}
            fallback_data={
              "This is a powerful framework built on top of NextJS that combines the benefits of a robust frontend library with a customizable content management system (CMS)."
            }
          />
        </div>
        <br />
        <br />
        <div className="" style={{ fontSize: "25px" }}>
          <DynamicContent
            dynamic_id="sub_intro"
            data={main_data}
            fallback_data={
              " Try editing contents of this page by clicking the edit icon next to them. You must be admin though, login from below"
            }
          />
        </div>

        <div className="stc_footer" style={{ fontSize: "20px" }}>
          If you want to edit contents, Go to
          <Link href={"/admin"}>
            <span style={{ color: "#c8235b" }}> admin panel from here</span>
          </Link>
        </div>
      </div>
    </>
  );
}
